### PR TITLE
Clean version of asctec_hl_gps

### PR DESCRIPTION
**Pull request by marija-p**
As per @enricgalceran's request, I've tidied up asctec_hl_gps by introducing a dependency to [geodetic_utils](ttps://github.com/ethz-asl/geodetic_utils). All the frame conversions are now performed using this new header-only package and redundant code has been removed (there was quite a lot of it!). I'm not the original author of this code, but I've also done some obvious re-formatting for readability and Google C++ Style. Let me know if anything else should be changed.

Despite these changes, the functionality of asctec_hl_gps should remain the same. It seems to build and work fine for me.

### CODE REVIEW

**Comment by helenol** [comment]
I think we'd ideally actually like to move everything you guys use out of asctec_hl_gps -> a different repo, since we are basically deprecating this whole repo. We've already gotten rid of all the other dependencies on asctec_mav_framework in other repos (as far as we know), and this is the last stuff remaining.
@markusachtelik ? @burrimi ? confirm?

**Comment by burrimi** [comment]
@helenol I think it's good to have it in here too, since a lot of people are still using this interface.

**Comment by enricgalceran** [comment]
@helenol I agree with @burrimi, plus this way we avoid having duplicated GPS conversion code.

**Comment by enricgalceran** [comment]
BTW @marija-p, I think you are already aware of this but you should prefix your branch names with feature/bugfix/cleanup/something.

**Comment by helenol** [comment]
@burrimi, @enricgalceran, sounds good to me. :)
Code looks much cleaner, thanks a lot for doing this! LGTM. (As soon as I fix the dependency in Jenkins).

**Comment by helenol** [comment]
test this please

**Comment by helenol** [comment]
Now will work once https://github.com/ethz-asl/geodetic_utils/pull/1 is merged.

**Comment by ffurrer** [comment]
lgtm

**Pull request merged**
